"""init_tables

Revision ID: acbf5d1037fe
Revises: 
Create Date: 2026-05-26 10:39:01.117488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'acbf5d1037fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200, collation='utf8mb4_unicode_ci'),
               comment='邮箱',
               existing_comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('admins', 'is_active',
               existing_type=mysql.TINYINT(),
               comment='是否激活 默认1',
               existing_comment='状态:激活1未激活0',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('admins', 'is_delete',
               existing_type=mysql.TINYINT(),
               comment='是否被删除 默认0',
               existing_comment='删除1 未删除0',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('computers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('computers', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('computers', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('computers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admins', 'is_delete',
               existing_type=mysql.TINYINT(),
               comment='删除1 未删除0',
               existing_comment='是否被删除 默认0',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('admins', 'is_active',
               existing_type=mysql.TINYINT(),
               comment='状态:激活1未激活0',
               existing_comment='是否激活 默认1',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('admins', 'email',
               existing_type=sa.String(length=200, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='邮箱地址',
               existing_comment='邮箱',
               existing_nullable=False)
    # ### end Alembic commands ###
